# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_REF_NAME"'
cache:
#  key: "$CI_COMMIT_SHA-$CI_COMMIT_REF_NAME"
  key: "$CI_JOB_REF_NAME"
  paths:
    - .m2
    - target
    - builds
  untracked: true

variables:
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Dmaven.repo.local=.m2 -Djava.awt.headless=true"
  MAVEN_CMD: "mvn -T 1C --batch-mode --fail-fast"
# Debug and tracing.
#  CI_DEBUG_TRACE: "true"
#  GIT_DEBUG_LOOKUP: "1"
#  GIT_TRACE: "1"
#  GIT_TRACE_PACKET: "1"
#  GIT_TRANSLOOP_DEBUG: "1"
#  GIT_TRANSPORT_HELPER_DEBUG: "1"

stages:
  - prepare
  - build
  - test
  #- coverage
  - quality
  - security

##########################################################
# PREPARE
##########################################################

prepare:cacherampup:
  image: maven:3-jdk-8
  stage: prepare
  script: "echo cache rampup"
  artifacts:
    paths:
    - .
    expire_in: 1 week

prepare:linter:
  image: maven:3-jdk-8
  stage: prepare
  script: "echo linter"
  artifacts:
    paths:
    - .
    expire_in: 1 week

##########################################################
# BUILD
##########################################################

build:maven:
  image: maven:3-jdk-8
  stage: build
  script: "$MAVEN_CMD -DskipTests=true -Dmaven.javadoc.skip=true clean install"
  artifacts:
    paths:
    - .
    expire_in: 1 week

##########################################################
# TEST
##########################################################

test:unit-testing:
  image: maven:3-jdk-8
  stage: test
  script: "$MAVEN_CMD -DskipTests=false -Dmaven.javadoc.skip=true test"
  artifacts:
    paths:
    - .
    expire_in: 1 week

test:mutation-testing:
  image: maven:3-jdk-8
  stage: test
  script: "echo mutation-test"
  artifacts:
    paths:
    - .
    expire_in: 1 week

test:end2end-testing:
  image: maven:3-jdk-8
  stage: test
  script: "echo end2end-test"
  artifacts:
    paths:
    - .
    expire_in: 1 week

##########################################################
# QUALITY
##########################################################

quality:codequality:
  image: maven:3.3.9-jdk-8-alpine
  stage: quality
  allow_failure: true
  script:
    - "$MAVEN_CMD org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dsonar.branch.name=$CI_COMMIT_REF_NAME -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=$SONAR_ORGANIZATION"

##########################################################
# SECURITY
##########################################################

security:retirejs:
  stage: security
  image: gruebel/retirejs
  allow_failure: true
  script:
    - retire --path . --outputformat json --includemeta
  artifacts:
    paths:
    - .
    expire_in: 1 week