# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_REF_NAME"'
cache:
#  key: "$CI_COMMIT_SHA-$CI_COMMIT_REF_NAME"
  key: "$CI_JOB_REF_NAME"
  paths:
    - .m2
    - target
    - builds
  untracked: true

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2 -Djava.awt.headless=true"
# Debug and tracing.
#  CI_DEBUG_TRACE: "true"
#  GIT_DEBUG_LOOKUP: "1"
#  GIT_TRACE: "1"
#  GIT_TRACE_PACKET: "1"
#  GIT_TRANSLOOP_DEBUG: "1"
#  GIT_TRANSPORT_HELPER_DEBUG: "1"

stages:
  - build
  #- test
  #- coverage
  - quality
  - security

##########################################################
# BUILD
##########################################################

build:maven:
  image: maven:3-jdk-8
  stage: build
  script: "mvn --batch-mode -DskipTests=true -Dmaven.javadoc.skip=true -B package"
  artifacts:
    paths:
    - .
    expire_in: 1 week

##########################################################
# QUALITY
##########################################################

quality:codequality:
  image: maven:3.3.9-jdk-8-alpine
  stage: quality
  allow_failure: true
  script:
    - mvn --batch-mode org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dsonar.branch.name=$CI_COMMIT_REF_NAME -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=$SONAR_ORGANIZATION

##########################################################
# SECURITY
##########################################################

security:retirejs:
  stage: security
  image: gruebel/retirejs
  allow_failure: true
  script:
    - retire --path . --outputformat json --includemeta
  artifacts:
    paths:
    - .
    expire_in: 1 week