language: java
dist: trusty

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.sonar/cache'

jdk:
  - oraclejdk8
#  - oraclejdk9
#  - oraclejdk10
#  - openjdk7
#  - openjdk8
#  - openjdk9
#  - openjdk10
#  - openjdk11

#before_install:
  #- export MAVEN_OPTS="-Xmx1024m"
  #- export MAVEN_OPTS="-DskipTests=true -Dmaven.javadoc.skip=true ${MAVEN_OPTS}"
  #- export MAVEN_OPTS="-Dlogback.configurationFile=../../build/logback-travis.xml ${MAVEN_OPTS}"
  #- export MAVEN_OPTS="-Dcoverage.port=random ${MAVEN_OPTS}"
  #- export MAVEN_OPTS="-Dcoverage.securePort=random ${MAVEN_OPTS}"


env:
  global:
    - REQUIRED_HEAP=1024m
    - SKIP_TESTS=true
    - SKIP_JAVADOC=true
    - SONAR_HOST_URL=https://sonarcloud.io

stages:
  - rampupcache
  - prepare
  - compile
  - sonarcloud
#  - test
#  - coverage
#

  #- mvn -q -pl jooby -am -Dsonar.branch.name=${TRAVIS_BRANCH} clean install org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar coveralls:report -P coverage
 # mvn -Dsonar.login=fcff19dd0c924736522c14558e35bb96c326141b -Dsonar.organization=feffi-github -DskipTests=true -Dmaven.javadoc.skip=true -pl jooby -am -Dsonar.host.url=https://sonarcloud.io clean install org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  #- "mvn -pl jooby -am clean install org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar"

jobs:
  include:

######################################################################################################

    - stage: rampupcache
      env:
        #- MAVEN_OPTS=-Xmx${REQUIRED_HEAP} -DskipTests=${SKIP_TESTS} -Dmaven.javadoc.skip=${SKIP_JAVADOC} -Dlogback.configurationFile=logback-travis.xml
      script:
        - "mvn dependency:resolve-plugins"

######################################################################################################

    - stage: prepare
      env:
        #- MAVEN_OPTS=-Xmx${REQUIRED_HEAP} -DskipTests=${SKIP_TESTS} -Dmaven.javadoc.skip=${SKIP_JAVADOC} -Dlogback.configurationFile=logback-travis.xml
      script:
        - "mvn clean"

######################################################################################################

    - stage: compile
      env:
        - MAVEN_OPTS=-Xmx${REQUIRED_HEAP} -DskipTests=${SKIP_TESTS} -Dmaven.javadoc.skip=${SKIP_JAVADOC} -Dlogback.configurationFile=logback-travis.xml
      script:
        - "mvn compile"
        #- "mvn compile -pl jooby -am"

######################################################################################################

#    - stage: test
#      env:
#        - MAVEN_OPTS=-Xmx1024m -Dlogback.configurationFile=logback-travis.xml
#      script:
#        - "mvn test"
#    - stage: coverage
#      env:
#        - MAVEN_OPTS=-Xmx1024m -Dlogback.configurationFile=logback-travis.xml -Dcoverage.port=random -Dcoverage.securePort=random
#      script:
#        - mvn -q coveralls:report -P coverage

######################################################################################################

    - stage: sonarcloud
          env:
            - MAVEN_OPTS=-Dsonar.branch.name=${TRAVIS_BRANCH} -Dsonar.host.url=${SONAR_HOST_URL}
          script:
            - "mvn -pl jooby -am org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar"
          addons:
            sonarcloud:
              organization: $SONAR_ORGANIZATION
              token: $SONAR_TOKEN

#branches:
#  only:
#    - master

#after_success:
#  - bash <(curl -s https://codecov.io/bash)